language: go
go:
- '1.5'
- '1.6'

addons:
  apt:
    packages:
      - libpcap-dev

branches:
  only:
    - master

env:
  global:
  - GO15VENDOREXPERIMENT=1

install: script/bootstrap
script:  script/test
