#!/bin/bash
set -euo pipefail

mkdir -p dist

executables=`go list -f "{{ .Name }}: {{ .ImportPath }}" ./... | grep "main:" | cut -d ' ' -f2`

for executable in ${executables[@]}; do
  name=`basename $executable`
  go build -o "dist/${name}" "$executable"
done
