#!/bin/bash
set -e

export GO15VENDOREXPERIMENT=1
which glide > /dev/null 2>&1 && exit 0

if test "Darwin" == "$(uname)"
  then brew install glide
fi

which glide > /dev/null 2>&1 || {
  wget https://github.com/Masterminds/glide/releases/download/0.9.0/glide-0.9.0-linux-amd64.tar.gz
  tar xvf glide-0.9.0-linux-amd64.tar.gz
  mkdir -p $GOPATH/bin
  cp linux-amd64/glide $GOPATH/bin && rm -rf linux-amd64
}

which glide > /dev/null 2>&1
